- 👋 Hi, I’m @MadhuSamhita
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...

<!---
MadhuSamhita/MadhuSamhita is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
Hi all!

I'm Samhita and I'm currently studying my 2nd btech in artificial intelligence and data science.

I'm interested in solving problems logically and I am really into codifying things as much as l can.

I learned C, data structures in my 1st btech.

Currently I'm learning java and R language.

I have some ideas related to probability and statistics on which I hope to build some projects.

Also, I have a lot of knowledge in fields of Indian history, culture, heritage, hindu mythology etc. which I hope to contribute to Wikimedia.

I basically know nothing much about GitHub and how to contribute to projects as a beginner.

I hope somebody can guide me!!

If you want to reach out to me, you can mail me: madhusamhitaganti@gmail.com

